DIGITAL-37: Migrate links paragraph templates.
GSA/digital-gov-drupal pull request #48
Opened 2024-11-21 19:31 UTC by omerida

## Jira ticket

[DIGITAL-37](https://cm-jira.usa.gov/browse/DIGITAL-37)

## Purpose

Adds paragraph_view_mode module.
Migrate template for featured links field display. Adds separate templates for default and featured links views of resources. Updates featured links template with correct markup. Switch shortcodes to use theme templates for resources.

It can be helpful to understand:
1. What the solution is,
2. Why this approach was chosen,
3. How you implemented the change
4. Possible limitations of this approach and alternate solution paths. -->

## Includes the following PRs that must be merged first

## Deployment and testing

### Local Setup

`bin/drush cim` to get paragraph type updates
`bin/drush cr` to refresh theme template cache

### QA/Testing instructions

Edit a topic page, add one or more internal and external resources
Confirm they use the expected HTML from the featured-links template
Override the title, summary for resources and confirm overrides are used

## Checklist for the Developer

- [x] A link to the JIRA ticket has been included above.
- [x] No merge conflicts exist with the target branch.
- [x] Automated tests have passed on this PR.
- [x] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-11-27 21:38 UTC, mattsqd requested changes
Please check the integration of the paragraphs on the topics node template

2024-12-10 21:30 UTC, omerida commented
@mattsqd do you need any more changes on this PR?

2024-12-11 17:24 UTC, mattsqd commented
> @mattsqd do you need any more changes on this PR?

Sorry, for the delay here. The input formatters were driving me crazy so I had to do some extra changes in your branch. I can merge now.

2024-12-11 17:25 UTC, mattsqd approved these changes

2024-12-11 17:25 UTC, mattsqd approved these changes

2024-12-11 17:25 UTC, merged